feature/UCAF-609/607-automated-bomb-screenshot-and-corruption-calculator
rettichlp/UnicacityAddon-1.12.2 pull request #614
Opened 2023-02-14 21:01 UTC by Gelegenheitscode

closes #609 
closes #607 

rettich seine komischen dreiecke sind auch weg

2023-02-18 11:44 UTC, rettichlp requested changes
Änderungen bitte übernehmen und testen, nächstes mal bitte getrennte Pull Requests für jedes Issue!

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        if (args.length < 1) {
```suggestion

        if (args.length < 1) {
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        String target = args[0];
```suggestion
        
        String target = args[0];
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        Betrag = wanted.getAmount() * 150;
```suggestion
        int money = wanted.getAmount() * 150;
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        int Betrag;
```suggestion
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        int Drugs;
```suggestion
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        int MethDrugs0;
```suggestion
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        int MethDrugs1;
```suggestion
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        int MethDrugs2;
```suggestion
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        Drugs = Betrag / 55;
```suggestion
        int drugs = money / 55;
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        MethDrugs0 = Betrag / 110;
```suggestion
        int methDrugs0 = money / 110;
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        MethDrugs1 = Betrag / 100;
```suggestion
        int methDrugs1 = money / 100;
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        MethDrugs2 = Betrag / 50;
```suggestion
        int methDrugs2 = money / 50;
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +                .of(Betrag + "$").color(ColorCode.AQUA).advance()
```suggestion
                .of(money + "$").color(ColorCode.AQUA).advance()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        p.sendMessage(Message.getBuilder()
```suggestion
        
        p.sendMessage(Message.getBuilder()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        p.sendMessage(Message.getBuilder()
```suggestion
        
        p.sendMessage(Message.getBuilder()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        p.sendMessage(Message.getBuilder()
```suggestion
        
        p.sendMessage(Message.getBuilder()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +                .of(Drugs + "g").color(ColorCode.AQUA).advance()
```suggestion
                .of(drugs + "g").color(ColorCode.AQUA).advance()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        p.sendMessage(Message.getBuilder()
```suggestion
        
        p.sendMessage(Message.getBuilder()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +                .of(MethDrugs0 + "g").color(ColorCode.AQUA).advance().space()
```suggestion
                .of(methDrugs0 + "g").color(ColorCode.AQUA).advance().space()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +                .of(MethDrugs1 + "g").color(ColorCode.AQUA).advance().space()
```suggestion
                .of(methDrugs1 + "g").color(ColorCode.AQUA).advance().space()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +                .of(MethDrugs2 + "g").color(ColorCode.AQUA).advance()
```suggestion
                .of(methDrugs2 + "g").color(ColorCode.AQUA).advance()
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/events/faction/terroristen/BombTimerEventHandler.java
> +            if (ConfigElements.getAutomatedBombScreenshot())  {
```suggestion
            
            if (ConfigElements.getAutomatedBombScreenshot())  {
```

2023-02-18 11:44 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/events/faction/terroristen/BombTimerEventHandler.java
> +            }
```suggestion
            }
            
```

2023-02-18 23:33 UTC, Gelegenheitscode commented
übernommen aber geht nd gucke morgen warum nicht

2023-02-18 23:55 UTC, Gelegenheitscode commented
ok gefixt

2023-02-19 20:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +
```suggestion
```

2023-02-19 20:16 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/fbi/KorruptionsrechnerCommand.java
> +        }
```suggestion
        }

```

2023-02-19 20:17 UTC, rettichlp approved these changes
Review ok

2023-02-19 20:20 UTC, merged