feature/UCAF-drugvault-info-messages
rettichlp/UnicacityAddon-1.12.2 pull request #619
Opened 2023-02-22 20:06 UTC by Gelegenheitscode

closes #618

2023-02-23 13:45 UTC, Gelegenheitscode commented
Note: UnicaCity wechselt bei der Standartnachricht von /asservatenkammer info immer die Reihenfolge der Reinheiten (Grund unbekannt), daher Pattern angepasst.

2023-02-24 21:15 UTC, rettichlp requested changes
Nur so bisl Kram, den Rettich will weil er sonst nicht gut schlafen kann

2023-02-24 21:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/base/text/PatternHandler.java
> +
Warum?

2023-02-24 21:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/events/faction/state/DrugMessageEventHandler.java
> +            Matcher drugVaultInfoMatcher = PatternHandler.DRUG_VAULT_INFO_PATTERN.matcher(msg);
```suggestion
            
            Matcher drugVaultInfoMatcher = PatternHandler.DRUG_VAULT_INFO_PATTERN.matcher(msg);
```

2023-02-24 21:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/events/faction/state/DrugMessageEventHandler.java
> +            Matcher drugVaultInfoLSDMatcher = PatternHandler.DRUG_VAULT_INFOLSD_PATTERN.matcher(msg);
```suggestion
            
            Matcher drugVaultInfoLSDMatcher = PatternHandler.DRUG_VAULT_INFOLSD_PATTERN.matcher(msg);
```

2023-02-24 21:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/events/faction/state/DrugMessageEventHandler.java
> +            Matcher drugVaultInfoTitleMatcher = PatternHandler.DRUG_VAULT_INFOTITLE_PATTERN.matcher(msg);
```suggestion
            
            Matcher drugVaultInfoTitleMatcher = PatternHandler.DRUG_VAULT_INFOTITLE_PATTERN.matcher(msg);
```

2023-02-24 21:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/base/text/PatternHandler.java
> +    public static final Pattern REVIVE_DONE_PATTERN = Pattern.compile("^[Karma] +1 Karma.");
```suggestion
```

2023-02-24 21:15 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/base/text/PatternHandler.java
> +
```suggestion
```

2023-02-24 21:20 UTC, rettichlp approved these changes
Review ok

2023-02-24 21:21 UTC, merged