feature/UCAF-/clear-[Spieler...]
rettichlp/UnicacityAddon-1.12.2 pull request #621
Opened 2023-02-24 21:47 UTC by Gelegenheitscode

closes #620

2023-02-24 22:14 UTC, rettichlp requested changes
Etwas kürzer geht noch

2023-02-24 22:14 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/polizei/ClearCommand.java
> +                .addToAllFromIndex(2, ForgeUtils.getOnlinePlayers())
Spieler sind immer standardmäßig ausgewählt. Du musst also keine Tabcompletion angeben

2023-02-24 22:14 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/polizei/ClearCommand.java
> +        List<String> players = Arrays.asList(args);
```suggestion
        Arrays.stream(args).forEach(player -> p.sendChatMessage("/clear " + player));
```

2023-02-24 22:14 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/polizei/ClearCommand.java
> +    private void clearWanteds(UPlayer issuer, List<String> players) {
Kann weg

2023-02-25 00:06 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/polizei/ClearCommand.java
> +        Arrays.stream(args).forEach(player -> p.sendChatMessage("/clear " + player));
```suggestion
        
        Arrays.stream(args).forEach(player -> p.sendChatMessage("/clear " + player));
```

2023-02-25 00:06 UTC, rettichlp commented on src/main/java/com/rettichlp/unicacityaddon/commands/faction/polizei/ClearCommand.java
> +
```suggestion
```

2023-02-25 00:07 UTC, rettichlp approved these changes
Review ok

2023-02-25 00:20 UTC, Gelegenheitscode commented
merge

2023-02-25 00:46 UTC, merged